задача 3го модуля. решил частично. тесты не проходит
js-tasks-ru/js-20210126_dmitrygreen pull request #2
Opened 2021-02-13 13:59 UTC by quantumRobin

2021-02-15 09:52 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +function chartTemplate(label, value, columns, link) {
почему данный метод находится за пределами класса?

2021-02-15 09:52 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +function columnsTemplate(data) {
почему данный метод находится за пределами класса?

2021-02-15 09:53 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +   columns += `<div style="--value: ${Math.round(item/2)}" data-tooltip="${item}%"></div>`; }
помните на занятии мы говорили о том что лучше использовать `map` вместо конкатенации строк. Напомните пожалуйста почему

2021-02-15 09:53 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +  constructor({data = '', label = orders, value = 344, link = '#'} = {}) {
`344` не может быть параметром по умолчанию. Следует заменить на 0

2021-02-15 09:54 UTC, dosandk requested changes
необходимо дать ответы на вопросы

2021-02-15 12:42 UTC, quantumRobin commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +function chartTemplate(label, value, columns, link) {
так учили на предидущем курсе. все функции шаблоны писались за пределами класса. чтобы не заграмождать класс и если нужно поменять шаблон он быстро снаружи меняеться и это не затрагивает класс. это то что я помню. да было сказано, что можно и внутри, но лучше снаружи... так я запомнил. ваш ответ по этому поводу исчерпал тему.

2021-02-15 12:43 UTC, quantumRobin commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +   columns += `<div style="--value: ${Math.round(item/2)}" data-tooltip="${item}%"></div>`; }
я только сегодня посмотрел лекцию за 9 февраля... поэтому сделал так как пришло в голову. теперь я в курсе что канкотенация это не очень. спасибо

2021-02-15 12:45 UTC, quantumRobin commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +  constructor({data = '', label = orders, value = 344, link = '#'} = {}) {
да. тут ошибка. в том плане что когда я сам делал, я не понял на счет скелетона. я досмотрел лекцию и разобрался.

2021-02-15 12:46 UTC, quantumRobin commented
> необходимо дать ответы на вопросы

лекцию досмотрел. разобрался со всем. переделаю все как у вас. потому что получается все что я написал как раз так делать и не следует. я не двигаюсь в обучении дальше пока не разберусь как все работает иначе какой смысл)

2021-02-16 13:05 UTC, dosandk approved these changes

2021-02-16 13:06 UTC, merged