решил модуль 5 и 6. тесты не проходят
js-tasks-ru/js-20210126_dmitrygreen pull request #3
Opened 2021-02-24 10:02 UTC by quantumRobin

2021-02-24 10:02 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-02-24 22:20 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      field = targetColumn.dataset.id;
не стоит переприсваивать аргументы функции, это плохая практика

2021-02-24 22:20 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      let targetColumn = event.target.closest('.sortable-table__cell[data-id]');
проверьте, здесь точно `let`?

2021-02-24 22:21 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      switch (order) {
подумайте, может в данном случае лучше заменить `switch...case` на объект?

2021-02-24 22:21 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    let elemBelow = document.elementFromPoint(event.pageX, event.pageY);
почему данные переменные объявлены через `let`?

2021-02-24 22:22 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.body.addEventListener('pointermove', this.pointerOnMove);
помните мы разбирали на занятии что событие `pointermove` должно навешиваться только в момент когда пользователь наводит курсор на релевантный элемент?

2021-02-24 22:23 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  show() {
а где логика показа нотификейшена не только внутри `document.body`?

2021-02-24 22:24 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    console.error('this.subElements', this.subElements);
не оставляйте консоли в PR

2021-02-24 22:24 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.sort = this.sort.bind(this);
помните алтернативнй способ сохранения корректной ссылки на `this`?

2021-02-24 22:25 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +   this.sort(null, this.defaultSortField, this.defaultSortOrder);
почему здесь первый аргумент `null`?

2021-02-24 22:26 UTC, dosandk requested changes
посмотрите комменты, внесите правки.
На вопросы нужно дать ответы

2021-02-25 22:55 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.defaultSortField = 'price';
почему сортировка по умолчанию это `price`? Ведь наш компонент может сортировать данные у которых нет колонки `price`

2021-02-26 08:38 UTC, quantumRobin commented on 06-events-practice/1-sortable-table-v2/index.js
> +      field = targetColumn.dataset.id;
тут я переприсваиваю изза того, что в моей логике самый первый сорт запускается из конструктора, потому и запуск с первым аргументом nul, когда еще айвент никакой не отработал => 
this.sort(null, this.defaultSortField, this.defaultSortOrder);
позже в сорт у меня уже логика строится на том, был ли айвент.
с логикой решения задач я не очень дружу, поэтому решил как пришло в голову, все же это лучше чем снова посмотреть у вас правильное решение)
ну я понял что логику надо менять... сейчас буду разбираться.
посоветуйте пожалуйста курс или книгу по логике решения задач в программировании)

2021-02-26 08:39 UTC, quantumRobin commented on 06-events-practice/1-sortable-table-v2/index.js
> +      let targetColumn = event.target.closest('.sortable-table__cell[data-id]');
тут конст) не знаю зачем лет написал. я помню - все что по коду дальше меняться не будет это конст.

2021-02-26 08:40 UTC, quantumRobin commented on 06-events-practice/1-sortable-table-v2/index.js
> +      switch (order) {
я чтото не помню как это делать и зачем тут это надо. попробую разобраться.

2021-02-26 08:40 UTC, quantumRobin commented on 06-events-practice/2-tooltip/index.js
> +    let elemBelow = document.elementFromPoint(event.pageX, event.pageY);
да тут тоже ошибка.. тут конст

2021-02-26 08:41 UTC, quantumRobin commented on 06-events-practice/2-tooltip/index.js
> +    document.body.addEventListener('pointermove', this.pointerOnMove);
не помню или я не смотрел еще лекцию где это разбиралось. поищу...

2021-02-26 08:44 UTC, quantumRobin commented on 05-dom-document-loading/1-notification/index.js
> +  show() {
вот поэтому у меня не проходит первый тест. я изначально не понял зачем нужно не в бади. можно же и в диве...) буду разбираться.

2021-02-26 08:44 UTC, quantumRobin commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    console.error('this.subElements', this.subElements);
ОК)

2021-02-26 08:44 UTC, quantumRobin commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.sort = this.sort.bind(this);
через стрелочную функцию... но я делаю и через байнд, просто чтобы не забыть оба варианта.

2021-02-26 08:45 UTC, quantumRobin commented on 06-events-practice/1-sortable-table-v2/index.js
> +   this.sort(null, this.defaultSortField, this.defaultSortOrder);
первый аргумент нулл потому что это первый сорт после рендера, когда еще не было никакого айвента, на этом у меня строится дальнейшая логика сорта.

2021-02-26 08:49 UTC, quantumRobin commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.defaultSortField = 'price';
ради эксперимента я ставил разные значения, просто забыл поменять. вообще получается что тут может быть любой филд. а что же тогда ставить по умолчанию на первой самой сортировке?

2021-02-26 10:00 UTC, quantumRobin commented on 06-events-practice/1-sortable-table-v2/index.js
> +      switch (order) {
нашел как это переделать... но тогда логика вся ломается. по идее должно так же как свитч работать. закоментировал пока что. не могу понять почему все ломается?

2021-02-26 10:00 UTC, quantumRobin commented on 06-events-practice/1-sortable-table-v2/index.js
> +      field = targetColumn.dataset.id;
ок. переделал...

2021-02-26 10:06 UTC, quantumRobin commented on 06-events-practice/2-tooltip/index.js
> +    document.body.addEventListener('pointermove', this.pointerOnMove);
да тут не имеет смысла нагружать движок пока курсор в любом другом месте документа.

2021-02-26 10:09 UTC, quantumRobin commented on 06-events-practice/1-sortable-table-v2/index.js
> +      field = targetColumn.dataset.id;
проходит тесты. но ведь все так же работает. как это повлияло на тесты не понятно...

2021-02-26 10:18 UTC, quantumRobin commented on 06-events-practice/1-sortable-table-v2/index.js
> +      switch (order) {
я так же прочел что вместо свитч по возможности лучше делать обж, но почему там не пишут. может вы объясняли на лекции и я просто до этого момента не дошел еще.

2021-02-26 10:26 UTC, quantumRobin commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.defaultSortField = 'price';
наверно лучше описать чтобы начальная сортировка делалась по первой колонке у которой найдется data-sortable="true"

2021-02-26 10:34 UTC, quantumRobin commented on 05-dom-document-loading/1-notification/index.js
> +  show() {
я и забыл что на разборе домашки за это говорили.

2021-03-01 17:02 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      field = targetColumn.dataset.id;
если есть необходимость вызвать один и тот же метод с разным количеством аргумента то есть 2 способа:
1й - необязательный аргумент передается последним:
```
someFunction(a, b, optional)
```
2й способ - пример с аргументом `event`

```
sort(event, this.defaultSortField, this.defaultSortOrder) 
```
передавать свойства класса нет необходиости, они и так доступны внутри метода через `this`.
Но вот если очень нужно передавать несколько аргументов и первый из них - опциональный, то следует создать обертку над данным методом:

```
this.sort(null, this.defaultSortField, this.defaultSortOrder);

const sortWrapper = (event, defaultSortField, defaultSortOrder) => { 
  // ... получить данные из `event`
  const sortField =  event.detail.sortField;
  const sortOrder = event.detail.sortOrder;

  sort(sortField, sortOrder);
};

const sort = (sortField, sortOrder) => {
  // ... some logic here
}
```

2021-03-01 17:03 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.defaultSortField = 'price';
да

2021-03-01 17:03 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    parent.append(this.element);
good 👍

2021-03-01 17:04 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.defaultSortField = 'title';
это значение нужно взять из `headersConfig` - первый объект из этого массива, используйте его `id`

2021-03-01 17:04 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    let field = this.defaultSortField;
`const`

2021-03-01 17:04 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
>      let text = elemBelow.dataset.tooltip;
это тоже `const`

2021-03-01 17:04 UTC, dosandk approved these changes

2021-03-01 17:05 UTC, merged